### ISSUE TITLE
New Forms v1.0 Comments

### ISSUE THREAD

**Issue by sayloo** [creativedisturbance/public-website#80] opened 2015-03-30 17:05 UTC
http://q1nm62.axshare.com/

Password: ArtSciLab1

**Comment by sayloo** [comment] 2015-03-30 18:59
Get rid of the podcast date.

**Comment by cassininazir** [comment] 2015-04-03 17:55
- Gender should be drop-down
- Form checking should be 
- Add a "Save" button until everything that is required is complete 
- Primary language should be drop-down 
- "Website" field should be clearer

**Comment by porteriffic** [comment] 2015-04-03 18:01
Producer's website
Language - Podcast Form
Multiple audio files
Studio - In Person

**Comment by heiwanalady** [comment] 2015-04-03 18:49
* Needs a "home" button at the top instead of the "back" button on the bottom of the page
* Spaces/text need to be bigger? Idk - design needs work
* Asterisks (or some kind of sign) for mandatory text input fields 
* Needs CD logo

**Comment by yvantina** [comment] 2015-04-06 00:04
my two cents for the new podcast info form:
- "existing channel (or not)" >> can a podcast be submitted for a channel that does not exist yet ? should this option be available ?
- "add audio file" >> does it implies that one can submit a podcast that has not been edited yet ? if so be careful for podcast in foreign language...I thought Dropbox was intended to be the place where a producer/host can upload a podcast..i'm confused..
- Producer's info are missing >> when a producer receives a notification (wufoo) it is helpful to know which podcasts are scheduled for her/his channel so s/he can anticipate in case there is any mistake..
- a bit confused by "podcast artwork" >> i thought we decided to not include any image due to possible copyright issues..
- parts of guest's info are missing (bio, website, pic..

please disregard this if i'm mistaken somewhere

**Comment by sayloo** [comment] 2015-04-07 20:50
Web Dev Meeting 4/7/15

3 sound files ( 2GB max)
Remove 2nd channel field - New podcast Form
16px font size
Need to figure out storage for audio files
Reference Images instead of podcast artwork
Isotope - Images for About Page 
Image --> Photo
New podcast n Guest Form - Test these out by April 24 on the Production Server

**Comment by coreysmart92** [comment] 2015-04-07 22:36
Sound Team Meeting 4/6/15

-Combine New Producer and New Channel
-Combine New Podcast and Co-Producer
-New Producer Form
  -Change Website to Website (if any)
  -No Podcast Artwork
  -Allow Audio File to have multiple file uploads
  -Change Method of Recording the Podcast to Location
  -Change Method of Recording the Podcast to Online, In Person, and Other

**Comment by coreysmart92** [comment] 2015-04-07 22:45
Sound Team Meeting 4/6/15

Change the Guest Release Form to a Voice Form:
-Add Bio
-Add Expertise
-Add Picture
-Keep normal Release Approval
-Link to New Podcast and New Channel Forms similar to WordPress

**Comment by cassininazir** [comment] 2015-04-14 20:28
Commence ta building!

**Comment by sayloo** [comment] 2015-05-13 20:49
![2](https://cloud.githubusercontent.com/assets/8712694/7620769/ad93f93a-f987-11e4-9d8b-6b182ca1c216.png)
![3](https://cloud.githubusercontent.com/assets/8712694/7620770/ad951d9c-f987-11e4-9abc-908c54db0681.png)
![4](https://cloud.githubusercontent.com/assets/8712694/7620771/ad960cf2-f987-11e4-9bdb-b97d2b82871f.png)
![1](https://cloud.githubusercontent.com/assets/8712694/7620772/ad997856-f987-11e4-8e1f-422f90df7965.png)

**Comment by sayloo** [comment] 2015-05-13 20:55
@cassininazir  - Design of the forms using bootstrap is almost done. Fixing few bugs related to jQuery. Samples of podcast and channel form is attached. I believe it is better to use PHP than rails (rails is faster than PHP) as for the former, anyone can log into phpmyadmin to access all the records. While for the latter, queries have to written to access the database records and field values. I do not htink everyone would be comfortable to use queries. Correct me if I am wrong.

**Comment by cassininazir** [comment] 2015-05-13 21:02
Wow! Very pleased to hear this.

Agree completely with your choice for PHP/MySQL over Rails.

Post to production server when you feel comfortable with the code. Would like the podcast production team to take a look at it as well.

Cassini Nazir

Clinical Assistant Professor,
School of Arts and Technology and Emerging Communication
The University of Texas at Dallas

**Comment by porteriffic** [comment] 2015-05-13 22:40
@sayloo @cassininazir Looking forward to trying out the new forms and implementing them! Thank you!

**Comment by cassininazir** [comment] 2015-05-19 16:36
Closing. The forms have been designed. Congrats, @sayloo

**Closed by cassininazir** 2015-05-19 16:36 UTC
Labels: Administrative, High Priority

**Comment by porteriffic** [comment] 2015-05-19 20:13
Yay! Thank you @sayloo !
